dist: trusty
language: android

android:
  components:
    - build-tools-28.0.3
    - android-28
    - add-on
    - extra
    - extra-google-google_play_services
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script: 
  - ./scripts/ci_unit_tests.sh

after_sucess:
- codecov
